# -*- coding: utf-8 -*-
"""Harsh.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17QSg6DajOPA1hYHfCy2LvyZJWZdLFrXs

page-1
"""

page1 = open("/content/Page1.txt", "r")

page1_content=page1.read()

#page1_content

words = list(filter(lambda word: not any(char.isdigit()
                                         for char in word), page1_content.split()))

#words

len(words)

page1_word = [*set(words)]

len(page1_word)

#page1_word

import string
l1 = [''.join(char for char in item
                    if char not in string.punctuation)
            for item in page1_word]
#l1:page1_final_word

l1=[x.lower() for x in l1]

"""Page-2"""

page2 = open("/content/Page2.txt", "r")

page2_content=page2.read()

#page2_content

words = list(filter(lambda word: not any(char.isdigit()
                                         for char in word), page2_content.split()))

#words

len(words)

page2_word = [*set(words)]

len(page2_word)

#page2_word

import string
l2 = [''.join(char for char in item
                    if char not in string.punctuation)
            for item in page2_word]
#l2:page2_final_word

l2=[x.lower() for x in l2]

"""Page-3

"""

page3 = open("/content/Page3.txt", "r")

page3_content=page3.read()

#page3_content

words = list(filter(lambda word: not any(char.isdigit()
                                         for char in word), page3_content.split()))

#words

len(words)

page3_word = [*set(words)]

len(page3_word)

#page3_word

import string
l3 = [''.join(char for char in item
                    if char not in string.punctuation)
            for item in page3_word]
#l3:page3_final_word

l3=[x.lower() for x in l3]

"""Other Modifications"""

d={}

h1=1
h2=2
h3=3
def check_l2(j):
    p=0
    for x in l2:
      if x == j:
        p=1
        l2.remove(j)
        break
    return p

def check_l3(k):
    h=0
    for y in l3:
      if y == k:
        h=1
        l3.remove(k)
        break
    return h
for i in l1:
    l2_ret=check_l2(i)
    l3_ret=check_l3(i)

    if l2_ret==1 and l3_ret==1:  #here all page
      #print(i,end=':')
      #print(h1,h2,h3,sep=',')
      new_data={i:[h1,h2,h3]}
      d.update(new_data)

    elif l2_ret==1: #here page-1 and page-2
      #print(i,end=':')
      #print(h1,h2,sep=',')
      new_data={i:[h1,h2]}
      d.update(new_data)

    elif l3_ret==1: #here page-1 and page-3
      #print(i,end=':')
      #print(h1,h3,sep=',')
      new_data={i:[h1,h3]}
      d.update(new_data)


    elif l2_ret==0 and l3_ret==0:  #here only page-1
      #print(i,end=':')
      #print(h1)
      new_data={i:[h1]}
      d.update(new_data)

for i in l2:
  l3_ret=check_l3(i)

  if l3_ret == 1: #here page-2 and page-3
    #print(i,end=':')
    #print(h2,h3,sep=',')
    new_data={i:[h2,h3]}
    d.update(new_data)

  elif l3_ret == 0: #here page-2
    #print(i,end=':')
    #print(h2)
    new_data={i:[h2]}
    d.update(new_data)

for i in l3: #here remaning page-3
  #print(i,end=':')
  #print(h3)
  new_data={i:[h3]}
  d.update(new_data)

"""Output"""

print("Word : Page Number")
print("-------------------")
for i in sorted(d):
   print(i,end=' : ')
   print(*d[i],sep=',')